x-project-name: &default-project-name
    name: project-teste

services:
    ####################################################################################################
    # PHP
    ####################################################################################################
    # php:
    #   build: .docker/php
    #   ports:
    #       - 5173:5173
    #   volumes:
    #       - .:/var/www:cached
    #   networks:
    #       - project-network

    ####################################################################################################
    # Nginx
    ####################################################################################################
    # nginx:
    #   image: nginx
    #   ports:
    #       - 9080:80
    #   volumes:
    #       - .:/var/www
    #       - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #       - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    #   depends_on:
    #       - php
    #   networks:
    #       - project-network

    # ####################################################################################################
    # POSTGRESS
    # ####################################################################################################
    postgres:
        container_name: postgresql
        image: postgres:17.2
        environment:
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./.docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - "25432:5432"
        restart: unless-stopped
        networks:
            - project-network

networks:
    project-network:
        driver: bridge

volumes:
    postgres-data:
