x-project-name: &default-project-name
    name: project-teste

services:
    # ####################################################################################################
    # POSTGRESS
    # ####################################################################################################
    postgres:
        container_name: postgresql
        image: postgres:17.2
        environment:
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./.docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - "25432:5432"
        restart: unless-stopped
        networks:
            - project-network

    ####################################################################################################
    # RabbitMQ
    ####################################################################################################
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: unless-stopped
        ports:
            - "5672:5672"   # RabbitMQ main port
            - "15672:15672" # Management UI
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        networks:
            - project-network
    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        depends_on:
            - postgres
            - rabbitmq
        networks:
            - project-network

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx:latest
        ports:
            - 9080:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - project-network



networks:
    project-network:
        driver: bridge

volumes:
    postgres-data:
